#!/bin/bash

# Install packages
sudo apt-get update
sudo apt-get install -y python3
sudo apt-get install -y ansible

# Download script to execute ansible tasks
uuid=$(uuidgen)
mkdir -p /tmp/ansible-${uuid}
cd /tmp/ansible-${uuid}
curl https://raw.githubusercontent.com/Elevennails/ansible/run-task.sh -o run-task.sh
chmod +x run-task.sh

# Download and execute ansible tasks
sudo /tmp/ansible-${uuid}/run-task.sh https://raw.githubusercontent.com/Elevennails/example/example.yml

# Cleanup
rm -rf /tmp/ansible-${uuid}
